config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] = 'Article eas successfully created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div class="card mb-3">
        <div class="article-title card-header">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body card-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
          <div class="article-actions">
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete",
                        article_path(article),
                        method: :delete,
                        data: {confirm: "Are you sure you want to delete the article?"},
                        class: "btn btn-xs btn-danger"
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for @article do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: "col-sm-2 col-form-label" %><br/>
        <div class="col-sm-12">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :description, class: "col-sm-2 col-form-label" %><br/>
        <div class="col-sm-12">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
      <div class="col-sm-12">
        [ <%= link_to "Back", articles_path %> ]
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="card col-sm-8 offset-sm-2">
  <ul class="listing">
    <div class="row center">
      <div class="col-md-4 offset-md-4">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li>
          <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
        </li>
      </div>
    </div>
  </ul>
  <h4 class="center description">
    <strong>
      Description:
    </strong>
  </h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-actions">
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete",
                article_path(@article),
                method: :delete,
                data: {confirm: "Are you sure you want to delete the article?"},
                class: "btn btn-xs btn-danger"
    %>
    <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://udemy.com">The Complete Ruby on Rails Developer</a> by <a href="http://mashrurhossain.com">Mashrur Hussain</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to"About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= "#{name}" %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "New article", new_article_path, class: "dropdown-item" %>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 class="display-4">ALPHA BLOG</h1>
  <%= link_to "Sign up now", "#", class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-sm-12">
      <div class="card alert-danger">
        <div class="card-header">
          <h2 class="card-title">
            <%= pluralize(obj.errors.count, "error") %>:
          </h2>
          <div class="card-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for @user do |f| %>
      <div class="form-group row">
        <%= f.label :username, class: "col-sm-2 col-form-label" %><br/>
        <div class="col-sm-12">
          <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :email, class: "col-sm-2 col-form-label" %><br/>
        <div class="col-sm-12">
          <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :password, class: "col-sm-2 col-form-label" %><br/>
        <div class="col-sm-12">
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-primary btn-lg") %>
        </div>
      </div>
      <div class="col-sm-12">
        [ <%= link_to "Back", articles_path %> ]
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All alpha Bloggers</h1>
<div align="center">
  <%= will_paginate %>
  <%= @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="card col-md-4 offset-md-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li>
            <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup for Alpha blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
  <div class="col-md-4 offset-md-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center">
  <%= @user.username %>'s articles
</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>